apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - djnd/deployment.yaml
  - djnd/ingress.yaml
  - djnd/service.yaml
  # - djnd/cronjobs/fetch_bluesky.yaml
  # - website-redirects/deployment.yaml
  # - website-redirects/ingress.yaml
  # - website-redirects/service.yaml
images:
  - name: danesjenovdan-staging
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-staging
    newTag: '40427eec29acac2a3e8f4878fc52c732dec97044'
  # - name: danesjenovdan-website-redirects
  #   newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-website-redirects
  #   newTag: '40427eec29acac2a3e8f4878fc52c732dec97044'
