apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - djnd/deployment.yaml
  - djnd/ingress.yaml
  - djnd/service.yaml
  - website-redirects/deployment.yaml
  - website-redirects/ingress.yaml
  - website-redirects/service.yaml
images:
  - name: danesjenovdan
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan
    newTag: 'efb16f4f720d2b65f7d7e7da9bc9dae80a8dcf16'
  - name: danesjenovdan-website-redirects
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-website-redirects
    newTag: 'efb16f4f720d2b65f7d7e7da9bc9dae80a8dcf16'
