apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - djnd/deployment.yaml
  - djnd/ingress.yaml
  - djnd/service.yaml
  # - djnd/cronjobs/fetch_bluesky.yaml
  # - website-redirects/deployment.yaml
  # - website-redirects/ingress.yaml
  # - website-redirects/service.yaml
images:
  - name: danesjenovdan-staging
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-staging
    newTag: 'f8e02db55d1f2dbc3bf96fb29958320a308474ea'
  # - name: danesjenovdan-website-redirects
  #   newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-website-redirects
  #   newTag: 'f8e02db55d1f2dbc3bf96fb29958320a308474ea'
