apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - djnd/deployment.yaml
  - djnd/ingress.yaml
  - djnd/service.yaml
  - website-redirects/deployment.yaml
  - website-redirects/ingress.yaml
  - website-redirects/service.yaml
images:
  - name: danesjenovdan
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan
    newTag: '0fd2f4c3d3f9051f17c45bd4b75e3c1deca226f9'
  - name: danesjenovdan-website-redirects
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-website-redirects
    newTag: '0fd2f4c3d3f9051f17c45bd4b75e3c1deca226f9'
