apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: danesjenovdan
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan
    newTag: 'c4f628cfe7e15b46881b5f31e60a2d23cc047f3e'
