apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: danesjenovdan
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan
    newTag: 'ad56fa1d678731dd7ba6feeb834c4d97c4124a47'
