apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - djnd/deployment.yaml
  - djnd/ingress.yaml
  - djnd/service.yaml
  - website-redirects/deployment.yaml
  - website-redirects/ingress.yaml
  - website-redirects/service.yaml
images:
  - name: danesjenovdan
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan
    newTag: '4804a1a2f4461e7869d80735ee6ce35d7e6613bf'
  - name: danesjenovdan-website-redirects
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-website-redirects
    newTag: '4804a1a2f4461e7869d80735ee6ce35d7e6613bf'
