apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danesjenovdan
resources:
  - djnd/deployment.yaml
  - djnd/ingress.yaml
  - djnd/service.yaml
  - website-redirects/deployment.yaml
  - website-redirects/ingress.yaml
  - website-redirects/service.yaml
images:
  - name: danesjenovdan
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan
    newTag: '99a507d7df0be25f982e4626afed559cc279dec1'
  - name: danesjenovdan-website-redirects
    newName: rg.fr-par.scw.cloud/djnd/danesjenovdan-website-redirects
    newTag: '99a507d7df0be25f982e4626afed559cc279dec1'
