apiVersion: v1
kind: Secret
metadata:
  name: danesjenovdan-secrets
type: Opaque
stringData:
  # DJANGO_DEBUG: ""
  DJANGO_SECRET_KEY: "secretkey_changeme"
  # DJANGO_STATIC_ROOT: ""
  # DJANGO_STATIC_URL_BASE: ""
  DJANGO_DATABASE_HOST: "host_changeme"
  DJANGO_DATABASE_PORT: "5432"
  DJANGO_DATABASE_NAME: "name_changeme"
  DJANGO_DATABASE_USERNAME: "username_changeme"
  DJANGO_DATABASE_PASSWORD: "password_changeme"
  # DJANGO_ENABLE_S3: "yes"
  # DJANGO_AWS_ACCESS_KEY_ID: "accesskeyid_changeme"
  # DJANGO_AWS_SECRET_ACCESS_KEY: "secretaccesskey_changeme"
