apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danesjenovdan-staging
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.middlewares: |
      traefik-redirect-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - staging.danesjenovdan.si
      secretName: danesjenovdan-staging-tls
  rules:
    - host: staging.danesjenovdan.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: danesjenovdan-staging
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danesjenovdan-staging-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - files.staging.danesjenovdan.si
      secretName: danesjenovdan-staging-nginx-tls
  rules:
    - host: files.staging.danesjenovdan.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: danesjenovdan-staging-nginx
                port:
                  number: 80
