apiVersion: v1
kind: Service
metadata:
  name: danesjenovdan-staging
spec:
  selector:
    app: danesjenovdan-staging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: danesjenovdan-staging-nginx
spec:
  selector:
    app: danesjenovdan-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
