# Generated by Django 4.2.10 on 2024-02-14 17:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_modularpage_description_modularpage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterpage",
            name="exposed",
            field=wagtail.fields.StreamField(
                [
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.CharBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("link", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="news",
            field=wagtail.fields.StreamField(
                [
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.CharBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("link", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
