# Generated by Django 4.2.10 on 2024-02-14 18:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_newsletterpage_exposed_newsletterpage_introduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [], blank=True, null=True, use_json_field=True, verbose_name="Moduli"
            ),
        ),
    ]
