# Generated by Django 4.2.10 on 2024-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_subtitle_modularpage_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
