# Generated by Django 4.2.10 on 2024-03-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_blogpage_modules_alter_modularpage_modules_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HeaderSettings",
            new_name="NavigationSettings",
        ),
        migrations.AlterModelOptions(
            name="navigationsettings",
            options={"verbose_name": "Navigacija", "verbose_name_plural": "Navigacija"},
        ),
    ]
