# Generated by Django 4.2.10 on 2024-03-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_navigationsettings_pages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
    ]
