# Generated by Django 4.2.10 on 2024-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_modularpage_modules_alter_pillarpage_modules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
