# Generated by Django 4.2.10 on 2024-03-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_modularpage_modules_alter_pillarpage_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoted',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.activity'),
        ),
        migrations.AlterField(
            model_name='promoted',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='promoted',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
