# Generated by Django 4.2.10 on 2024-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_activitycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillarpage',
            name='activities_title',
            field=models.TextField(blank=True),
        ),
    ]
