# Generated by Django 4.2.10 on 2024-05-24 10:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_homepage_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularpage',
            name='subpages',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
