# Generated by Django 4.2.10 on 2024-06-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_blogpage_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletterpage',
            old_name='exposed',
            new_name='promoted',
        ),
    ]
