# Generated by Django 4.2.10 on 2024-06-04 10:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_pillarpage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
