# Generated by Django 4.2.10 on 2024-06-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0044_rename_exposed_newsletterpage_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
