# Generated by Django 4.2.10 on 2024-06-06 10:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_blogpage_short_description_newsletterpage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='promoted_blogs',
            field=wagtail.fields.StreamField([('blogpage', wagtail.blocks.PageChooserBlock(page_type=['home.BlogPage']))], blank=True, null=True, use_json_field=True, verbose_name='Povezani zapisi'),
        ),
    ]
