# Generated by Django 4.2.10 on 2024-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_newsletterpage_promoted_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterpage',
            name='promoted',
        ),
    ]
