# Generated by Django 4.2.10 on 2024-06-06 10:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0047_homepage_focus_areas_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterpage",
            name="exposed",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="promoted_blogs",
            field=wagtail.fields.StreamField(
                [
                    (
                        "blogpage",
                        wagtail.blocks.PageChooserBlock(page_type=["home.BlogPage"]),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Povezani zapisi",
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="focus_areas",
            field=wagtail.fields.StreamField(
                [
                    (
                        "focus_area",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Ikona"
                                    ),
                                ),
                                (
                                    "color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("white", "Bela"),
                                            ("mint", "Meta"),
                                            ("red", "Rdeča"),
                                            ("green", "Zelena"),
                                            ("blue", "Modra"),
                                            ("yellow", "Rumena"),
                                            ("lavender", "Sivka"),
                                        ],
                                        label="Barva",
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        label="Zunanja povezava", required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Podstran", required=False
                                    ),
                                ),
                            ],
                            label="Fokus",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Fokusi",
            ),
        ),
        migrations.CreateModel(
            name="NewsletterListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("lead", models.TextField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
