# Generated by Django 4.2.10 on 2024-06-11 10:19

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_remove_newsletterpage_promoted_blogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pillarpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
