# Generated by Django 4.2.10 on 2024-06-13 11:45

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_blogpage_category_alter_blogpage_pillar_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.activitycategory', verbose_name='Kategorije'),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='pillar_page',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.pillarpage', verbose_name='Tematski sklopi'),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='project',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.activityproject', verbose_name='Projekti'),
        ),
    ]
