# Generated by Django 4.2.10 on 2024-06-19 10:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0066_alter_homepage_modules_alter_modularpage_modules_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="source",
        ),
        migrations.AlterField(
            model_name="activity",
            name="note",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
