# Generated by Django 4.2.10 on 2024-06-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0068_activity_promoted"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "Bela"),
                            ("mint", "Meta"),
                            ("red", "Rdeča"),
                            ("green", "Zelena"),
                            ("blue", "Modra"),
                            ("yellow", "Rumena"),
                            ("lavender", "Sivka"),
                        ],
                        default="white",
                        max_length=255,
                        verbose_name="Barva",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
