# Generated by Django 4.2.10 on 2024-07-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0071_alter_navigationsettings_pages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory",
            options={
                "ordering": ["order"],
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
            },
        ),
        migrations.AddField(
            model_name="activitycategory",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
