# Generated by Django 4.2.10 on 2024-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_activitycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityproject',
            options={'ordering': ['order'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekti'},
        ),
        migrations.AddField(
            model_name='activityproject',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
