# Generated by Django 4.2.15 on 2024-08-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0076_blogpage_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglistingpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="modularpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="newsletterlistpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="ourworkpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="pillarpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="supportpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
        migrations.AddField(
            model_name="teampage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
    ]
