# Generated by Django 4.2.15 on 2024-10-21 11:25

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0078_newsletterpage_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="new_pages",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                                (
                                    "show_languages",
                                    wagtail.blocks.MultipleChoiceBlock(
                                        choices=[
                                            ("en", "Angleščina"),
                                            ("sl", "Slovenščina"),
                                        ],
                                        label="Pokaži v jezikih",
                                    ),
                                ),
                                (
                                    "subpages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        label="Stran"
                                                    ),
                                                ),
                                                (
                                                    "show_languages",
                                                    wagtail.blocks.MultipleChoiceBlock(
                                                        choices=[
                                                            ("en", "Angleščina"),
                                                            ("sl", "Slovenščina"),
                                                        ],
                                                        label="Pokaži v jezikih",
                                                    ),
                                                ),
                                            ]
                                        ),
                                        default=[],
                                        label="Podstrani",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
                verbose_name="Strani",
            ),
        ),
    ]
