# Generated by Django 4.2.15 on 2024-11-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0080_remove_navigationsettings_pages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "verbose_name": "Aktivnost (Projekt)",
                "verbose_name_plural": "Aktivnosti (Projekti)",
            },
        ),
        migrations.AlterField(
            model_name="promoted",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.activity",
                verbose_name="Aktivnost (Projekt)",
            ),
        ),
        migrations.AlterField(
            model_name="promoted",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Če so polja prazna in obstaja Aktivnost (Projekt), se uporabijo podatki Aktivnosti (Projekta)",
                verbose_name="Naslov",
            ),
        ),
    ]
