# Generated by Django 4.2.15 on 2024-11-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0081_alter_activity_options_alter_promoted_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pillarpage",
            name="filter_icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
