# Generated by Django 5.0.10 on 2025-01-14 10:56

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0082_pillarpage_filter_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="pillars",
            field=wagtail.fields.StreamField(
                [("page", wagtail.blocks.PageChooserBlock("home.PillarPage"))],
                use_json_field=True,
                verbose_name="Stebri",
            ),
        ),
    ]
