# Generated by Django 5.1.4 on 2025-05-16 08:54

import wagtail.fields
from django.db import migrations, models

import home.models.snippets


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0084_alter_activity_locale_alter_activitycategory_locale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloglistingpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("text_content_block", 8),
                    ("newsletter_block", 10),
                    ("support_block", 10),
                    ("promoted_block", 12),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 2),
                                ("link", 3),
                                ("page_link", 4),
                                ("color", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {"max_num": 1, "min_num": 0}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("text", 1), ("button", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barvna shema",
                        },
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("color_scheme", 9)]], {}),
                    11: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 11)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="focus_areas",
            field=wagtail.fields.StreamField(
                [("focus_area", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Ime"}),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Ikona"},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva",
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Podstran", "required": False},
                    ),
                    5: ("wagtail.blocks.TextBlock", (), {"label": "Povezana poved"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 0),
                                ("image", 1),
                                ("color", 2),
                                ("url", 3),
                                ("page", 4),
                                ("linked_sentence", 5),
                            ]
                        ],
                        {"label": "Fokus"},
                    ),
                },
                null=True,
                verbose_name="Fokusi",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("contact_block", 0),
                    ("pillars_block", 5),
                    ("networks_block", 11),
                    ("text_content_block", 18),
                    ("table_block", 21),
                    ("donors_block", 22),
                    ("financial_information_block", 24),
                    ("promoted_block", 26),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.PillarPage"]},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("pillars", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("link", 7), ("image", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 6), ("networks", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 1),
                                ("link", 13),
                                ("page_link", 14),
                                ("color", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"max_num": 1, "min_num": 0},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("text", 6), ("button", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("table", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("current_donors", 10), ("past_donors", 10)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Letna vsebinska in finančna poročila",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("reports_url", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 25)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="modularpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="modularpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("contact_block", 0),
                    ("pillars_block", 5),
                    ("networks_block", 11),
                    ("text_content_block", 18),
                    ("table_block", 21),
                    ("donors_block", 22),
                    ("financial_information_block", 24),
                    ("promoted_block", 26),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.PillarPage"]},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("pillars", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("link", 7), ("image", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 6), ("networks", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 1),
                                ("link", 13),
                                ("page_link", 14),
                                ("color", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"max_num": 1, "min_num": 0},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("text", 6), ("button", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("table", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("current_donors", 10), ("past_donors", 10)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Letna vsebinska in finančna poročila",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("reports_url", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 25)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="newsletterlistpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="ourworkpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="pillarpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="pillarpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("contact_block", 0),
                    ("pillars_block", 5),
                    ("networks_block", 11),
                    ("text_content_block", 18),
                    ("table_block", 21),
                    ("donors_block", 22),
                    ("financial_information_block", 24),
                    ("promoted_block", 26),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.PillarPage"]},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("pillars", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("link", 7), ("image", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 6), ("networks", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 1),
                                ("link", 13),
                                ("page_link", 14),
                                ("color", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"max_num": 1, "min_num": 0},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("text", 6), ("button", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("table", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("current_donors", 10), ("past_donors", 10)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Letna vsebinska in finančna poročila",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("reports_url", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 25)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="supportpage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
        migrations.AlterField(
            model_name="teampage",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Bela"),
                    ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                    ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                    ("green", "Zelena (Digitalne pravice in pismenost)"),
                    ("blue", "Modra (Skupnost in solidarnost)"),
                    ("yellow", "Rumena (Participacija in vključenost)"),
                    ("lavender", "Vijolična (Odgovornost in transparentnost)"),
                ],
                default="white",
                max_length=255,
                verbose_name="Barva",
            ),
        ),
    ]
