# Generated by Django 5.2.3 on 2025-06-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0085_alter_bloglistingpage_color_alter_blogpage_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterlistpage",
            name="is_programmers_newsletter",
            field=models.BooleanField(
                default=False, verbose_name="Ali je to programerski novičnik"
            ),
        ),
    ]
