# Generated by Django 5.2.3 on 2025-06-13 10:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0086_newsletterlistpage_is_programmers_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterpage",
            name="custom_sections",
            field=wagtail.fields.StreamField(
                [("section", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("list", "List"), ("grid", "Grid")]},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("description", 0), ("image", 2), ("link", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_name", 0),
                                ("section_description", 0),
                                ("section_display", 1),
                                ("section_items", 5),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="news",
            field=wagtail.fields.StreamField(
                [("article", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("description", 0), ("image", 1), ("link", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="promoted",
            field=wagtail.fields.StreamField(
                [("article", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("description", 0), ("image", 1), ("link", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
