# Generated by Django 5.2.3 on 2025-07-25 09:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0088_alter_newsletterpage_custom_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterpage",
            name="custom_sections",
            field=wagtail.fields.StreamField(
                [("section", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("list", "List"),
                                ("grid", "Grid"),
                                ("text", "Text"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ul", "ol"]},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("description", 2), ("image", 3), ("link", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_name", 0),
                                ("section_description", 0),
                                ("section_display", 1),
                                ("section_items", 6),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
