# Generated by Django 5.2.3 on 2025-07-28 12:51

import home.models.snippets
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0090_alter_blogpage_modules_alter_homepage_modules_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("contact_block", 0),
                    ("pillars_block", 5),
                    ("networks_block", 11),
                    ("text_content_block", 19),
                    ("table_block", 22),
                    ("donors_block", 23),
                    ("financial_information_block", 24),
                    ("promoted_block", 26),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.PillarPage"]},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("pillars", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("link", 7), ("image", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 6), ("networks", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 1),
                                ("link", 14),
                                ("page_link", 15),
                                ("color", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {"min_num": 0}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("text", 13), ("button", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("table", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("current_donors", 10), ("past_donors", 10)]],
                        {},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("title", 1)]], {}),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 25)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="modularpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("contact_block", 0),
                    ("pillars_block", 5),
                    ("networks_block", 11),
                    ("text_content_block", 19),
                    ("table_block", 22),
                    ("donors_block", 23),
                    ("financial_information_block", 24),
                    ("promoted_block", 26),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.PillarPage"]},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("pillars", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("link", 7), ("image", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 6), ("networks", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 1),
                                ("link", 14),
                                ("page_link", 15),
                                ("color", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {"min_num": 0}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("text", 13), ("button", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("table", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("current_donors", 10), ("past_donors", 10)]],
                        {},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("title", 1)]], {}),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 25)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="pillarpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    ("contact_block", 0),
                    ("pillars_block", 5),
                    ("networks_block", 11),
                    ("text_content_block", 19),
                    ("table_block", 22),
                    ("donors_block", 23),
                    ("financial_information_block", 24),
                    ("promoted_block", 26),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.StructBlock", [[]], {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["home.PillarPage"]},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("pillars", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("link", 7), ("image", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 6), ("networks", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Zunanja povezava", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Povezava na stran", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "Bela"),
                                ("mint", "Modrozelena (DJND logo, Projekti, ...)"),
                                ("red", "Rdeča (Občasnik, Podpri nas, ...)"),
                                ("green", "Zelena (Digitalne pravice in pismenost)"),
                                ("blue", "Modra (Skupnost in solidarnost)"),
                                ("yellow", "Rumena (Participacija in vključenost)"),
                                (
                                    "lavender",
                                    "Vijolična (Odgovornost in transparentnost)",
                                ),
                            ],
                            "label": "Barva gumba",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 1),
                                ("link", 14),
                                ("page_link", 15),
                                ("color", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {"min_num": 0}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("text", 13), ("button", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("table", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("current_donors", 10), ("past_donors", 10)]],
                        {},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("title", 1)]], {}),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (home.models.snippets.Promoted,),
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("promoted_snippet", 25)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Moduli",
            ),
        ),
    ]
