# Generated by Django 5.2.10 on 2026-01-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0091_alter_homepage_modules_alter_modularpage_modules_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
            },
        ),
        migrations.RenameField(
            model_name="activitycategory",
            old_name="order",
            new_name="sort_order",
        ),
    ]
