# Generated by Django 5.2.10 on 2026-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0092_alter_activitycategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory",
            options={"verbose_name": "Kategorija", "verbose_name_plural": "Kategorije"},
        ),
        migrations.AlterField(
            model_name="activitycategory",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
