# Generated by Django 5.2.10 on 2026-01-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0093_alter_activitycategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityproject",
            options={"verbose_name": "Projekt", "verbose_name_plural": "Projekti"},
        ),
        migrations.RenameField(
            model_name="activityproject",
            old_name="order",
            new_name="sort_order",
        ),
    ]
