# Generated by Django 5.2.10 on 2026-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0094_alter_activityproject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityproject",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
