# Generated by Django 6.0.4 on 2026-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0095_alter_activityproject_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
