# Generated by Django 6.0.4 on 2026-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0096_activitycategory_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
