# Generated by Django 6.0.4 on 2026-05-22 21:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0097_activityproject_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255, unique=True)),
                ("post_url", models.URLField()),
                (
                    "raw_html",
                    wagtail.fields.StreamField(
                        [("raw_html", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.RawHTMLBlock", (), {})},
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Objava na družbenem omrežju",
                "verbose_name_plural": "Objave na družbenem omrežju",
            },
        ),
    ]
