name: Check formatting
on:
  push:
    branches:
      - "v3-dev"
jobs:
  check_python_formatting:
    name: Check Python formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install black isort

      - name: Check formatting with black
        run: |
          (cd ./djnd && black . --check --diff)

      - name: Check formatting with isort
        run: |
          (cd ./djnd && isort . --check --diff --profile black)